### ISSUE TITLE
[在线转换]: 编码模块Ui变更 

### ISSUE THREAD

**Issue by ythyhvh** [imc-ux/AdvancedReact#12]
### Describe the problem

整段一行，行数太多

### Describe the proposed solution

一行分多列显示， 重新排版

### Importance

would make my life easier

**Comment by Cheesanse** [comment]
计划今天完成

**Comment by Cheesanse** [comment]
### 这个变动的性质是？
- [X] New feature
- [ ] Bug fix
- [ ] Refactoring
- [ ] Branch merge
- [ ] Other (about what?)
### 相关 Issue
1. resolve #12   

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [X] 代码格式化已进行
- [X] 代码开发基准核对完成
- [X] 样式设计已确认或无样式变动
 
### 概述
修改编码模块布局和按钮样式
